### ISSUE TITLE
Version 1.2 isn't published to Jenkins Plugins

### ISSUE THREAD

**Issue by grv87** [jenkinsci/github-pr-comment-build-plugin#2]
https://plugins.jenkins.io/github-pr-comment-build states that I should use version 1.2 with 2.x SCM API-related plugins. However, I couldn't find version 1.2 neither in https://updates.jenkins.io/stable-2.46/update-center.json nor in https://updates.jenkins.io/experimental/update-center.json. Could you publish it, or publish instructions how to install it?

P.S. Since change of dependencies is breaking, it makes sense to increment major version. I.e. release it as 2.0 instead of 1.2.

**Comment by bluesliverx** [comment]
Well I feel sheepish - I remember I had some test failures (for no reason whatsoever) and I couldn't get it to publish correctly, and then likely my computer restarted and I forgot I was even doing the release.

I'm actually quite glad 1.2 never made it out, since 2.0 is the right way to go as you said.  I only realized it after attempting to release 1.2 so I thought it was a done deal at that point.  I'll work on this.

**Comment by bluesliverx** [comment]
It should be released now. The update center json only updates once an hour or something, so it's not updated yet.  But it is in the repo: https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/github-pr-comment-build/2.0

I went with 2.0 and updated the wiki page with the new info.

**Comment by grv87** [comment]
Thanks a lot!

**Comment by bluesliverx** [comment]
Looks like the update site JSON is correct now, even though the wiki doesn't seem to know the latest is 1.1 yet for some reason.
