### ISSUE TITLE
 review dosent seem to work

### ISSUE THREAD

**Issue by ofirshtrull** [jenkinsci/github-pr-comment-build-plugin#23]
Hi I don't see much documentation regarding the review option,

i tried to test this by adding a reviewer and having them approve but no job was triggered

**Comment by ofirshtrull** [comment]
also maybe ad function to work on labels...

**Comment by bluesliverx** [comment]
Did you set up the hooks properly and add the property to the job config?

The env variables would be a separate issue, I believe there may already be one asking for env vars actually.

**Comment by Gregy** [comment]
The problem here is that Jenkins doesn't create the webhooks correctly on it's own. We use github multibranch pipeline job and it usually creates the webhooks github-side on it's own. Unfortunatelly it doesn't ask github to send the review statuses so the review trigger doesn't work unless you check the "Pull request review comments" event by hand in the github webhook settings. And this change gets undone when Jenkins recreates the webhook so you have to redo it from time to time.

**Comment by bluesliverx** [comment]
@ofirshtrull is your problem described by @Gregy? I'm not sure what it would take to add webhooks and don't have time to look at this at the moment. PRs are absolutely welcome though if someone has else the time.

**Comment by ofirshtrull** [comment]
I honestly to remmber this at all,
And i dont work at the same company any more
