### ISSUE TITLE
Does the latest version support trigger building in multibranch pipeline project?

### ISSUE THREAD

**Issue by wangchaoxiang** [jenkinsci/github-pr-comment-build-plugin#39]
Jenkins Version : CloudBees Jenkins Enterprise 2.249.31.0.5-fixed.

**Comment by bluesliverx** [comment]
Are you seeing specific problems? I know of no conflicts as of yet.

**Comment by ainoya** [comment]
It may be hook event trigger problem. In Jenkins Version: 2.327 / This Plugin version: 61.v49f749d31d98, `Discover branches` strategy doesn't setup `ISSUE_COMMENT` event trigger(I confirmed this behavior from logs.). 

![image](https://user-images.githubusercontent.com/2300438/147846245-fb482e54-a058-4b4d-82b7-a54202f15f51.png)

I used the `Discover pull requests from origin` strategy instead of `Discover branches` and it worked fine.

**Comment by wangchaoxiang** [comment]
Thanks for your help and i will try.
