### ISSUE TITLE
Programmatic configuration

### ISSUE THREAD

**Issue by chrylis** [jenkinsci/github-pr-comment-build-plugin#5]
Relating to #4, is there a way to configure this plugin programmatically, as from the `triggers` block?

The use case is that we would like to be able to add new repositories through the automatic scan and not need any on-server manual configuration. Instead, we could place a standard Jenkinsfile in new repositories and have the trigger configured automatically when the scan finds it.

**Comment by bluesliverx** [comment]
@chrylis, the only option here is to configure it programmatically with the job dsl plugin or Jenkins Job Builder (if it's still around).  We generate our jobs programmatically with the job dsl plugin and add the branch property there.  It will not work from a Jenkinsfile for the reasons I mentioned in #4.

**Comment by bluesliverx** [comment]
To expand the explanation a bit more - the multibranch plugin actually creates jobs and their triggers on the fly based on info from github.  A jenkinsfile has no ties into the multibranch plugin to be able to control this kind of behavior.  If they have added a way, that's great, let me know and I'll look into it.  But as far as I know it is quite against the principles of the multibranch framework that we're working in to be able to control this from Jenkinsfiles directly.

The job dsl plugin can do it since it can set the branch property as it generates the multibranch job.

**Comment by chrylis** [comment]
Thanks for the explanation. It really seems like CloudBees has charged ahead with their multibranch model without considering a number of in-use setups.
