### ISSUE TITLE
Build PR every time AFTER comment

### ISSUE THREAD

**Issue by MichalPloski** [jenkinsci/github-pr-comment-build-plugin#6]
Currently we have two options to modify plugin behaviour:
a) Trigger build after specific comment
b) Trugger build after PR is updated

I would like to have option to merge those two options in a following way:
a) User comment Pull Request and Build is triggered. Then this PR is marked 
b) Marked PR is then updated automatically every time commit is done

This differ from b) in a way that not every PR is updated but those ones that are previously marked by user - this allows us to remove unnecessary load as we don't want to build all active PRs

**Comment by bluesliverx** [comment]
You probably could do this with pipeline scripts as it is today if you setup a build to build after any comment (`.*`) and then change the configuration through the `properties` call (not sure what this looks like in declarative pipeline since we don't use it).  Alternatively, if you have a global pipeline library set up, you could use it to add an additional Action to the raw build itself, and then check for that action on subsequent builds to see if anything needs to be done.

In our usage of our, we actually use two different multibranch pipeline jobs for each module in our system.  The first multibranch job takes care of the heavy lifting of the build itself, and is only triggered from commit changes or a very specific message like "REBUILD".  The second multibranch job runs a very quick, very small job on every PR comment that does some other things for us.  You could use a similar setup to prevent comments from causing too many builds.
